apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiB...
      server: https://<cluster-endpoint>
    name: cluster-1
contexts:
  - context:
      cluster: cluster-1
      user: gke_ci-cd-demo-part2_cluster-1_us-central1-shradhasaxena129@gmail.com
    name: cluster-1
current-context: cluster-1
kind: Config
preferences: {}
users:
  - name: gke_ci-cd-demo-part2_cluster-1_us-central1-shradhasaxena129@gmail.com
    user:
        name: gcp
