apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiB...
      server: https://<cluster-endpoint>
    name: <cluster-name>
contexts:
  - context:
      cluster: <cluster-name>
      user: gke_<project-name>_<cluster-name>_<zone>-<user-name>
    name: <cluster-name>
current-context: <cluster-name>
kind: Config
preferences: {}
users:
  - name: gke_<project-name>_<cluster-name>_<zone>-<user-name>
    user:
      auth-provider:
        config:
          cmd-args: config config-helper --format=json
          cmd-path: /usr/lib/google-cloud-sdk/bin/gcloud
          expiry-key: '{.credential.token_expiry}'
          token-key: '{.credential.access_token}'
        name: gcp
