apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiB...
      server: https://<cluster-endpoint>
    name: cluster-1
contexts:
  - context:
      cluster: cluster-1
      user: gke_ci-cd-demo-part2_cluster-1_us-central1-shradhasaxena129@gmail.com
    name: cluster-1
current-context: cluster-1
kind: Config
preferences: {}
users:
  - name: gcp
    user:
      auth-provider:
        config:
          cmd-args: config config-helper --format=json
          cmd-path: /usr/lib/google-cloud-sdk/bin/gcloud
          expiry-key: '{.credential.token_expiry}'
          token-key: '{.credential.access_token}'
      client-certificate: ci-cd-demo-part2-290c71ddafb2.json
      client-key: /path/to/your-key.key
