apiVersion: v1
kind: Service
metadata:
  name: hello-application-java-17
spec:
  selector:
    app: hello-application-java-17
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080