name: Deploy to GKE

on: push

env:
  IMAGE_NAME: ghcr.io/shradhasaxena129/my-app/web-server:latest
  GKE_PROJECT: your-gke-project
  GKE_CLUSTER: your-gke-cluster
  GKE_NAMESPACE: your-gke-namespace
  KUBECONFIG: ${{ secrets.GKE_KUBECONFIG }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

#      - name: Build and push Docker image
#        env:
#          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#        run: |
#          echo $DOCKER_PASSWORD | docker login ghcr.io -u $DOCKER_USERNAME --password-stdin
#          docker buildx build --push --tag $IMAGE_NAME .

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

#      - name: Set up Google Cloud SDK
#        uses: google-github-actions/setup-gcloud@v0.5.0
#        with:
#          version: 'latest'
#          service_account_key: ${{ secrets.GKE_SA_KEY }}
#
#      - name: Configure kubectl
#        run: |
#          echo "$KUBECONFIG" | base64 --decode > kubeconfig.yaml
#          gcloud auth activate-service-account --key-file=kubeconfig.yaml
#          gcloud container clusters get-credentials $GKE_CLUSTER --project $GKE_PROJECT --zone your-gke-zone
#
#      - name: Deploy to GKE
#        run: |
#          kubectl apply -f path/to/your/deployment.yaml --namespace $GKE_NAMESPACE
