name: Deploy to GKE

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/<username>/<repository>/<image-name>:latest
  GKE_PROJECT: your-gke-project
  GKE_CLUSTER: your-gke-cluster
  GKE_NAMESPACE: your-gke-namespace
  KUBECONFIG: ${{ secrets.GKE_KUBECONFIG }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: shradhasaxena129
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo 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 | docker login ghcr.io -u shradhasaxena129 --password-stdin
          docker buildx build --push --tag $IMAGE_NAME .

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.5.0
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GKE_SA_KEY }}

      - name: Configure kubectl
        run: |
          echo "$KUBECONFIG" | base64 --decode > kubeconfig.yaml
          gcloud auth activate-service-account --key-file=kubeconfig.yaml
          gcloud container clusters get-credentials $GKE_CLUSTER --project $GKE_PROJECT --zone your-gke-zone

      - name: Deploy to GKE
        run: |
          kubectl apply -f path/to/your/deployment.yaml --namespace $GKE_NAMESPACE
