name: Create and publish a Docker image

on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GKE_PROJECT: github-actions-ghcr
  GKE_CLUSTER: ghcr-cluster-1
  GKE_NAMESPACE: github-actions-ghcr.svc.id.goog
  KUBECONFIG: ${{ secrets.GKE_KUBECONFIG }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.5.0
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GKE_SA_KEY }}

      - name: Configure kubectl
        run: |
          echo "$KUBECONFIG" | base64 --decode > kubeconfig.yaml
          gcloud auth activate-service-account --key-file=kubeconfig.yaml
          gcloud container clusters get-credentials $GKE_CLUSTER --project $GKE_PROJECT --zone us-central1

      - name: Deploy to GKE
        run: |
          kubectl apply -f path/to/your/deployment.yaml --namespace $GKE_NAMESPACE