name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

# Environment variables available to all jobs and steps in this workflow
env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GKE_CLUSTER: deployment-cluster-sdk
  GKE_NAMESPACE: demo-application
  GKE_ZONE: asia-southeast1-a



jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 19
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 19
      - run: mvn clean install --batch-mode --errors --fail-at-end
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: GKE-deployment-0.0.1-SNAPSHOT.jar
          path: target/
  build-docker-image:
    name: build-docker
    needs: setup-build-deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Retrieve saved jar
        uses: actions/download-artifact@v2
        with:
          name: GKE-deployment-0.0.1-SNAPSHOT.jar
          path: target/
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Use gcloud CLI'
        run: |
          gcloud auth configure-docker
      # Build the Docker image
      - name: Build
        run: |
          docker build -t gke-deployment-ci-cd .
      # Tag the Docker image
      - name: Tag
        run: |
          docker tag gke-deployment-ci-cd gcr.io/$PROJECT_ID/gke-deployment-ci-cd

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |
          docker push gcr.io/my-kubernetes-project-389604/gke-deployment-ci-cd
            # Push the Docker image to Google Container Registry

  deploy-to-gke:
    needs: build-docker-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: kubectl - Google Cloud GKE cluster.
        uses: ameydev/gke-kubectl-action@master
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIAL }}
          CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
          ZONE_NAME: asia-southeast1-a
        with:
          args: apply -f k8s/

